# Generated by Django 6.0.5 on 2026-05-28 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='remote_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='remote_etag',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='remote_uid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
